### ISSUE TITLE
use as NPM package

### ISSUE THREAD

**Issue by grinono** [geoblink/web-scraper-chrome-extension#1]
when i import the package to my Meteor > Nodejs server side. 

`function scrapeJSDOM (sitemapInfo, options = {})`
i got the error that `options = {}` is not allowed. It this a compiler thing?

```
options = {}
function scrapeJSDOM (sitemapInfo, options = {})
```
i tried to define the variable like above, it fixes the issue but then their are tons of others. Any idea how to fix this? Or any recommendation about an environment on what it is running correctly would be great as well.

**Comment by furstenheim** [comment]
What version of Node are you using? Default parameters are part of Node.js since version [6](https://stackoverflow.com/a/41507712)

**Comment by grinono** [comment]
the local node was 8 but figured meteor was in 4.3 or something.. fixed it with a later version.. thanks
