### ISSUE TITLE
Fix errors in documentation / examples

### ISSUE THREAD

**Issue by tripu** [geoblink/web-scraper-chrome-extension#2]
(cf https://github.com/martinsbalodis/web-scraper-chrome-extension/pull/202)

It was already mentioned on that PR upstream that the package name is wrong [in the README](https://github.com/geoblink/web-scraper-chrome-extension#headless-mode) (and therefore [on npm](https://www.npmjs.com/package/web-scraper-headless), too): it should be `web-scraper-headless`, not `webscraper-headless`.

Apart from that, I don't get why the only example is suggesting testing against [`http://test.lv/`](http://test.lv/). It's a particularly ugly and weird (HTML 4.01) web page&hellip;

Anyway, the suggested selector doesn't find anything on the page:

```javascript
selectors: [
  {
    'id': 'a',
    'selector': '#scraper-test-one-page a',
    'multiple': false,
    type: 'SelectorText',
    'parentSelectors': [
      '_root'
    ]
  }
]
```

Am I doing anything wrong?

Can we have a few examples that are correct and representative?

**Comment by furstenheim** [comment]
Thanks tripu, I've fixed the typo on the require.

As for the example, it was a mock example (straight from the tests) to avoid relying on a third web. It was indeed confusing, so I've changed it with a real example. https://github.com/geoblink/web-scraper-chrome-extension/commit/e3e7de1d9ddce1efb3473fbd87a9d419673947d3

Hope that it helps
